/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampil;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author SHINDY OEMARDY
 */
public class Tiket extends javax.swing.JFrame {

   private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public Tiket() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }
     protected void kosong(){
        txtkd.setText("");
        cbkelas.setSelectedItem(null);
        cbmas.setSelectedItem(null);
        cbpen.setSelectedItem(null);
        cbtujuan.setSelectedItem(null);
        txttgl.setText("");
        cbjam.setSelectedItem(null);
        txtbiaya.setText("");
        txtcari.setText("");
        
    }
     protected void aktif(){
        txtkd.requestFocus();
        cbkelas.setSelectedItem(null);
        cbmas.setSelectedItem(null);
        cbpen.setSelectedItem(null);
        cbtujuan.setSelectedItem(null);        
        cbjam.setSelectedItem(null);
    }
     protected void datatable(){
        Object[] Baris = {"no","kelas","maskapai", "penerbangan","tujuan", "tanggal", "jam", "biaya" };
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();            
        try{
            String sql = "SELECT * FROM tiket WHERE id_tiket like '%"+cariitem+"%' or kelas like '%"+cariitem+"%' order by id_tiket asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7),
                    hasil.getString(8)
                });
            }
          tabletiket.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal di panggil"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtkd = new javax.swing.JTextField();
        txtbiaya = new javax.swing.JTextField();
        txttgl = new javax.swing.JTextField();
        cbkelas = new javax.swing.JComboBox<>();
        cbmas = new javax.swing.JComboBox<>();
        cbpen = new javax.swing.JComboBox<>();
        cbtujuan = new javax.swing.JComboBox<>();
        cbjam = new javax.swing.JComboBox<>();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabletiket = new javax.swing.JTable();
        backGround1 = new tampil.BackGround();
        bcari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 36)); // NOI18N
        jLabel1.setText("TIKET");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("NO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Kelas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 94, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Maskapai");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 125, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Penerbangan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 162, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Tujuan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("tanggal");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 94, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("jam");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 125, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Biaya");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 162, -1, -1));

        txtkd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtkd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdActionPerformed(evt);
            }
        });
        jPanel1.add(txtkd, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 57, 270, -1));

        txtbiaya.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtbiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbiayaActionPerformed(evt);
            }
        });
        jPanel1.add(txtbiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 159, 193, -1));

        txttgl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txttgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttglActionPerformed(evt);
            }
        });
        jPanel1.add(txttgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 91, 193, -1));

        cbkelas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "ekonomi", "bisnis", "pemeritahan", " " }));
        jPanel1.add(cbkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 91, 270, -1));

        cbmas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbmas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Lion Air", "Garuda Indonesia", "Sriwijaya Air" }));
        jPanel1.add(cbmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 125, 271, -1));

        cbpen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbpen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "siap terbang", "belum siap" }));
        jPanel1.add(cbpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 159, 261, -1));

        cbtujuan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbtujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "1. Nanggroe Aceh Darussalam Banda Aceh", "2. Sumatra Utara Medan", "3. Sumatra Selatan Palembang", "4. Sumatra Barat Padang", "5. Bengkulu Bengkulu", "6. Riau Pekanbaru", "7. Kepulauan Riau Tanjung Pinang", "8. Jambi Jambi", "9. Lampung Bandar Lampung", "10. Bangka Belitung  Pangkal Pinang", "11. Banten Serang", "12 DKI Jakarta Jakarta", "13. Jawa Barat Bandung", "14. Jawa Tengah Semarang", "15. DI Yogyakarta Yogyakarta", "16. Jawa Timur Surabaya", "17. Kalimantan Timur Samarinda", "18. Kalimantan Barat Pontianak", "19. Kalimantan Tengah Palangka Raya", "20. Kalimantan Selatan Banjarbaru", "21. Kalimantan Utara Tanjung Selor", "22. Bali Denpasar", "23. Nusa Tenggara Timur Kupang", "24. Nusa Tenggara Barat Mataram", "25. Gorontalo Gorontalo", "26. Sulawesi Barat Mamuju", "27 Sulawesi Tengah Palu", "28. Sulawesi Utara Manado", "29. Sulawesi Tenggara Kendari", "30. Sulawesi Selatan Makassar", "31. Maluku Utara Sofifi", "32. Maluku Ambon", "33. Papua Barat Manokwari", "34. Papua Jayapura", "35. Papua Selatan Kabupaten Merauke", "36. Papua Tengah Kabupaten Nabire", "37. Papua Pegunungan Kabupaten Jayawijaya" }));
        jPanel1.add(cbtujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 57, 193, -1));

        cbjam.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "06.05 AM", "11.20 AM", "16.45 PM", "18.00 PM", "19.20 PM", "20.35 PM" }));
        jPanel1.add(cbjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 125, 193, -1));

        bsimpan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 193, -1, -1));

        bubah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bubah.setText("EDIT");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 193, -1, -1));

        bhapus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 193, -1, -1));

        bbatal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 193, -1, -1));

        bkeluar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bkeluar.setText("KEMBALI");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtcari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 231, 414, -1));

        tabletiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabletiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletiketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabletiket);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 267, 620, 110));

        bcari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bcari.setText("CARI");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backGround1Layout = new javax.swing.GroupLayout(backGround1);
        backGround1.setLayout(backGround1Layout);
        backGround1Layout.setHorizontalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGround1Layout.createSequentialGroup()
                .addContainerGap(535, Short.MAX_VALUE)
                .addComponent(bcari)
                .addGap(50, 50, 50))
        );
        backGround1Layout.setVerticalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGround1Layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(bcari)
                .addGap(130, 130, 130))
        );

        jPanel1.add(backGround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkdActionPerformed

    private void txtbiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbiayaActionPerformed

    private void txttglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttglActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
      kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
      datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "INSERT INTO tiket VALUES (?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtkd.getText());            
            stat.setString(2, cbkelas.getSelectedItem().toString());
            stat.setString(3, cbmas.getSelectedItem().toString());
            stat.setString(4, cbpen.getSelectedItem().toString());
            stat.setString(5, cbtujuan.getSelectedItem().toString());
            stat.setString(6, txttgl.getText());
            stat.setString(7, cbjam.getSelectedItem().toString());
            stat.setString(8, txtbiaya.getText());            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            kosong();
            txtkd.requestFocus();
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal di simapan"+e);
        }
        datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
      String sql = "UPDATE tiket SET kelas=?,maskapai=?, penerbangan=?, tujuan=?, tgl=?, jam=?, biaya=? WHERE id_tiket='"+txtkd.getText()+"'";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);                        
            stat.setString(1, cbkelas.getSelectedItem().toString());
            stat.setString(2, cbmas.getSelectedItem().toString());
            stat.setString(3, cbpen.getSelectedItem().toString());
            stat.setString(4, cbtujuan.getSelectedItem().toString());
            stat.setString(5, txttgl.getText());
            stat.setString(6, cbjam.getSelectedItem().toString());
            stat.setString(7, txtbiaya.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
            kosong();
            txtkd.requestFocus();
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal di ubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void tabletiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletiketMouseClicked
      int bar = tabletiket.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        
        txtkd.setText(a);
        cbkelas.setSelectedItem(b);
        cbmas.setSelectedItem(c);
        cbpen.setSelectedItem(d);
        cbtujuan.setSelectedItem(e);
        txttgl.setText(f);
        cbjam.setSelectedItem(g);
        txtbiaya.setText(h);
        txtcari.setText(i);
    }//GEN-LAST:event_tabletiketMouseClicked

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
     int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus data ini?", "konfirm dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0){
            String sql = "DELETE FROM tiket WHERE id_tiket='"+txtkd.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
                kosong();
                txtkd.requestFocus();
            } catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal di hapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tampil.BackGround backGround1;
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JComboBox<String> cbjam;
    private javax.swing.JComboBox<String> cbkelas;
    private javax.swing.JComboBox<String> cbmas;
    private javax.swing.JComboBox<String> cbpen;
    private javax.swing.JComboBox<String> cbtujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabletiket;
    private javax.swing.JTextField txtbiaya;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtkd;
    private javax.swing.JTextField txttgl;
    // End of variables declaration//GEN-END:variables
}
